import './style.css';

const canvas = document.querySelector<HTMLCanvasElement>('#game')!;
const ui = document.querySelector<HTMLDivElement>('#ui')!;
const ctx = canvas.getContext('2d')!;

const W = 1200, H = 700, field = { x: 70, y: 70, w: 1060, h: 560, goalH: 190 };
type Vec={x:number;y:number};
type Player={p:Vec;v:Vec;r:number;color:string;name:string;side:number;boost:number;cool:number;phase:number;action:boolean};
const keys=new Set<string>();
let mode:'bot'|'pvp'='bot', difficulty:'easy'|'normal'|'hard'='normal';
let state:'menu'|'difficulty'|'settings'|'playing'|'result'='menu', sound=true,music=false;
let p1:Player, p2:Player, ball={p:{x:600,y:350},v:{x:0,y:0},r:13};
let score=[0,0], timeLeft=120, last=performance.now(), goalUntil=0;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const norm=(x:number,y:number)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d,d}};
function resetPositions(){p1={p:{x:350,y:350},v:{x:0,y:0},r:24,color:'#28d8ff',name:'PLAYER 1',side:1,boost:0,cool:0,phase:0,action:false};p2={p:{x:850,y:350},v:{x:0,y:0},r:24,color:'#ff527a',name:mode==='bot'?'BOT':'PLAYER 2',side:-1,boost:0,cool:0,phase:0,action:false};ball={p:{x:600,y:350},v:{x:0,y:0},r:13}}
resetPositions();
function beep(freq:number,dur=.08,type:OscillatorType='sine'){if(!sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
function screen(html:string){ui.innerHTML=html}
function menu(){state='menu';screen(`<div class="screen"><div class="panel"><h1 class="logo">FOOTBALL<span>ARENA</span></h1><p class="tag">FAST. CLEAN. ONE BALL. ONE WINNER.</p><div class="buttons"><button class="btn primary" data-a="bot">PLAY VS BOT</button><button class="btn" data-a="pvp">PLAY VS PLAYER</button><button class="btn" data-a="settings">SETTINGS</button></div></div></div>`);wire()}
function difficultyScreen(){state='difficulty';screen(`<div class="screen"><div class="panel"><h2 style="font:800 48px 'Barlow Condensed';margin:0 0 8px">SELECT DIFFICULTY</h2><p class="tag">Choose your opponent.</p><div class="buttons"><button class="btn ${difficulty==='easy'?'selected':''}" data-d="easy">EASY <small>CASUAL</small></button><button class="btn ${difficulty==='normal'?'selected':''}" data-d="normal">NORMAL <small>BALANCED</small></button><button class="btn ${difficulty==='hard'?'selected':''}" data-d="hard">HARD <small>ELITE</small></button><button class="btn primary" data-a="start">KICK OFF</button><button class="btn back" data-a="menu">BACK</button></div></div></div>`);wire()}
function settingsScreen(){state='settings';screen(`<div class="screen"><div class="panel"><h2 style="font:800 48px 'Barlow Condensed';margin:0 0 24px">SETTINGS</h2><div class="buttons"><button class="btn" data-a="sound">SOUND: ${sound?'ON':'OFF'}</button><button class="btn" data-a="music">MUSIC: ${music?'ON':'OFF'}</button><button class="btn back" data-a="menu">BACK</button></div></div></div>`);wire()}
function start(){score=[0,0];timeLeft=120;goalUntil=0;resetPositions();state='playing';screen(`<div class="hud"><div class="score">P1 <b id="s1">0</b> — <b id="s2">0</b> P2</div><div class="clock" id="clock">2:00</div></div><button class="pause" data-a="menu">×</button><div class="goal" id="goal">GOAL!</div><div class="mobile"><div class="pad"><button class="key" data-k="ArrowLeft">←</button><button class="key" data-k="ArrowDown">↓</button><button class="key" data-k="ArrowUp">↑</button><button class="key" data-k="ArrowRight">→</button></div><div class="actions"><button class="key" data-k="Enter">KICK</button></div></div>`);wire();beep(520,.12,'square')}
function result(){state='result';const win=score[0]===score[1]?'DRAW':score[0]>score[1]?'YOU WIN':'YOU LOSE';screen(`<div class="screen"><div class="panel result"><h2>${win}</h2><p>FINAL SCORE&nbsp;&nbsp; ${score[0]} — ${score[1]}</p><div class="buttons"><button class="btn primary" data-a="start">REMATCH</button><button class="btn" data-a="menu">MAIN MENU</button></div></div></div>`);wire();beep(win==='YOU WIN'?880:win==='YOU LOSE'?180:440,.35,'triangle')}
function wire(){ui.querySelectorAll<HTMLButtonElement>('[data-a]').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='bot'){mode='bot';difficultyScreen()}else if(a==='pvp'){mode='pvp';start()}else if(a==='settings'){settingsScreen()}else if(a==='sound'){sound=!sound;settingsScreen()}else if(a==='music'){music=!music;settingsScreen()}else if(a==='start'){start()}else if(a==='menu'){menu()}});ui.querySelectorAll<HTMLButtonElement>('[data-d]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.d as typeof difficulty;difficultyScreen()});ui.querySelectorAll<HTMLButtonElement>('[data-k]').forEach(b=>{const k=b.dataset.k!;b.onpointerdown=()=>keys.add(k);b.onpointerup=()=>keys.delete(k);b.onpointercancel=()=>keys.delete(k);b.onpointerleave=()=>keys.delete(k)})}
window.addEventListener('keydown',e=>{keys.add(e.key);if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter'].includes(e.key))e.preventDefault()});window.addEventListener('keyup',e=>keys.delete(e.key));
function inputFor(first:boolean){let x=0,y=0,action=false;if(first){x=(keys.has('d')?1:0)-(keys.has('a')?1:0);y=(keys.has('s')?1:0)-(keys.has('w')?1:0);action=keys.has(' ')}else{x=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);y=(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0);action=keys.has('Enter')}return{x,y,action}}
function botInput(){const threat=ball.p.x>610;let tx=ball.p.x,ty=ball.p.y;const g={x:field.x+field.w,y:H/2};if(difficulty==='hard'){tx=threat?ball.p.x+(g.x-ball.p.x)*.22:ball.p.x-25;ty=ball.p.y+(g.y-ball.p.y)*.22}else if(difficulty==='normal'){tx=threat?ball.p.x-30:ball.p.x;ty=ball.p.y}else{tx=ball.p.x+Math.sin(performance.now()/850)*55;ty=ball.p.y+Math.cos(performance.now()/1050)*40}const n=norm(tx-p2.p.x,ty-p2.p.y);let action=false;const close=norm(ball.p.x-p2.p.x,ball.p.y-p2.p.y).d<p2.r+ball.r+20;if(close&&p2.cool<=0){const goalX=field.x+5,goalY=H/2;const aim=norm(goalX-ball.p.x,goalY-ball.p.y);action=true;(botInput as any)._aim=aim}return{x:n.x,y:n.y,action}}
function kick(p:Player, bot=false){const n=norm(ball.p.x-p.p.x,ball.p.y-p.p.y);if(n.d<p.r+ball.r+18&&p.cool<=0){let aim=n;if(bot){const goalX=field.x+5,goalY=H/2;aim=norm(goalX-ball.p.x,goalY-ball.p.y);if(difficulty==='easy'&&Math.random()<.35)aim=norm(aim.x+(Math.random()-.5)*1.1,aim.y+(Math.random()-.5)*1.1);if(difficulty==='normal')aim=norm(aim.x+(Math.random()-.5)*.35,aim.y+(Math.random()-.5)*.35)}const power=bot?(difficulty==='hard'?590:difficulty==='normal'?510:390):520;ball.v.x=aim.x*power+p.v.x*.18;ball.v.y=aim.y*power+p.v.y*.18;p.cool=.38;beep(180,.06,'square')}}
function update(dt:number){if(state!=='playing')return;timeLeft-=dt;if(timeLeft<=0){timeLeft=0;result();return}const i1=inputFor(true),i2=mode==='bot'?botInput():inputFor(false);for(const [p,i,bot] of [[p1,i1,false],[p2,i2,mode==='bot']] as [Player,{x:number;y:number;action:boolean},boolean][]) {const d=Math.hypot(i.x,i.y);const boost=p===p1&&keys.has('Shift');const speed=boost?355:(bot&&difficulty==='hard'?310:250);if(d>0){p.v.x+=(i.x/d*speed-p.v.x)*Math.min(1,dt*11);p.v.y+=(i.y/d*speed-p.v.y)*Math.min(1,dt*11)}else{p.v.x*=Math.pow(.03,dt);p.v.y*=Math.pow(.03,dt)}p.p.x=clamp(p.p.x+p.v.x*dt,field.x+35,field.x+field.w-35);p.p.y=clamp(p.p.y+p.v.y*dt,field.y+35,field.y+field.h-35);p.cool=Math.max(0,p.cool-dt);p.phase+=dt*Math.max(.4,Math.hypot(p.v.x,p.v.y)/75);if(i.action)kick(p,bot)}
let dx=p2.p.x-p1.p.x,dy=p2.p.y-p1.p.y,d=Math.hypot(dx,dy);if(d<48){const nx=dx/(d||1),ny=dy/(d||1),push=(48-d)/2;p1.p.x-=nx*push;p1.p.y-=ny*push;p2.p.x+=nx*push;p2.p.y+=ny*push;const rel=(p1.v.x-p2.v.x)*nx+(p1.v.y-p2.v.y)*ny;if(rel>0){p1.v.x-=nx*rel*.55;p1.v.y-=ny*rel*.55;p2.v.x+=nx*rel*.55;p2.v.y+=ny*rel*.55}}
for(const p of [p1,p2]){dx=ball.p.x-p.p.x;dy=ball.p.y-p.p.y;d=Math.hypot(dx,dy);if(d<p.r+ball.r){const nx=dx/(d||1),ny=dy/(d||1);ball.p.x=p.p.x+nx*(p.r+ball.r);ball.p.y=p.p.y+ny*(p.r+ball.r);const approach=ball.v.x*nx+ball.v.y*ny;if(approach<0){ball.v.x-=nx*approach*1.55;ball.v.y-=ny*approach*1.55}ball.v.x+=p.v.x*.16;ball.v.y+=p.v.y*.16}}
ball.p.x+=ball.v.x*dt;ball.p.y+=ball.v.y*dt;ball.v.x*=Math.pow(.25,dt);ball.v.y*=Math.pow(.25,dt);const top=field.y+14,bottom=field.y+field.h-14;if(ball.p.y<top){ball.p.y=top;ball.v.y=Math.abs(ball.v.y)*.72}if(ball.p.y>bottom){ball.p.y=bottom;ball.v.y=-Math.abs(ball.v.y)*.72}const gt=H/2-field.goalH/2,gb=H/2+field.goalH/2;if(ball.p.x<field.x+5){if(ball.p.y>gt&&ball.p.y<gb){score[1]++;onGoal()}else{ball.p.x=field.x+5;ball.v.x=Math.abs(ball.v.x)*.72}}if(ball.p.x>field.x+field.w-5){if(ball.p.y>gt&&ball.p.y<gb){score[0]++;onGoal()}else{ball.p.x=field.x+field.w-5;ball.v.x=-Math.abs(ball.v.x)*.72}}}
function onGoal(){goalUntil=performance.now()+1000;beep(760,.15,'sawtooth');setTimeout(()=>{if(state==='playing')resetPositions()},550)}
function rr(x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawField(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#123b35');g.addColorStop(1,'#082d29');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#0d523f';rr(field.x,field.y,field.w,field.h,24);ctx.save();ctx.globalAlpha=.07;for(let x=field.x;x<field.x+field.w;x+=70){ctx.fillStyle=x%140?'#fff':'#000';ctx.fillRect(x,field.y,70,field.h)}ctx.restore();ctx.strokeStyle='#d9f8e755';ctx.lineWidth=3;ctx.strokeRect(field.x,field.y,field.w,field.h);ctx.beginPath();ctx.moveTo(W/2,field.y);ctx.lineTo(W/2,field.y+field.h);ctx.stroke();ctx.beginPath();ctx.arc(W/2,H/2,78,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#dfffea';ctx.beginPath();ctx.arc(W/2,H/2,4,0,Math.PI*2);ctx.fill();for(const side of [-1,1]){const x=side<0?field.x:field.x+field.w-160;ctx.strokeRect(x,H/2-125,160,250);ctx.strokeRect(side<0?field.x:field.x+field.w-80,H/2-55,80,110);ctx.fillStyle='#eefbf5';ctx.fillRect(side<0?field.x-34:field.x+field.w,H/2-95,34,190)}ctx.fillStyle='#eaf9f0';ctx.font='700 12px Inter';ctx.fillText('P1',field.x+16,field.y+28);ctx.fillText('P2',field.x+field.w-40,field.y+28)}
function drawPlayer(p:Player){ctx.save();ctx.translate(p.p.x,p.p.y);const moving=Math.hypot(p.v.x,p.v.y)>30,bob=moving?Math.sin(p.phase*1.7)*2:0;ctx.shadowColor='#0008';ctx.shadowBlur=18;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,22,25,9,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=p.color;rr(-19,0,38,31,11);ctx.fill();ctx.fillStyle='#f5c9a9';ctx.beginPath();ctx.arc(0,-12+bob,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#18202a';ctx.beginPath();ctx.arc(0,-17+bob,14,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 10px Inter';ctx.textAlign='center';ctx.fillText(p.side>0?'1':'2',0,19);ctx.restore()}
function drawBall(){ctx.save();ctx.translate(ball.p.x,ball.p.y);ctx.rotate(performance.now()/500);ctx.shadowColor='#0008';ctx.shadowBlur=14;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,ball.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#14202b';for(let i=0;i<5;i++){const a=i*Math.PI*2/5;ctx.beginPath();ctx.arc(Math.cos(a)*5,Math.sin(a)*5,3.2,0,Math.PI*2);ctx.fill()}ctx.restore()}
function render(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);if(state==='playing'){drawField();drawPlayer(p1);drawPlayer(p2);drawBall();if(performance.now()<goalUntil){ctx.save();ctx.fillStyle='#fff';ctx.globalAlpha=Math.max(0,(goalUntil-performance.now())/1000);ctx.font='900 86px "Barlow Condensed"';ctx.textAlign='center';ctx.shadowColor='#000';ctx.shadowBlur=28;ctx.fillText('GOAL!',W/2,H/2-120);ctx.restore()}const c=document.querySelector('#clock');if(c)c.textContent=`${Math.floor(timeLeft/60)}:${String(Math.ceil(timeLeft%60)).padStart(2,'0')}`;const s1=document.querySelector('#s1');const s2=document.querySelector('#s2');if(s1)s1.textContent=String(score[0]);if(s2)s2.textContent=String(score[1])}}
function loop(now:number){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}
menu();requestAnimationFrame(loop);
